### ISSUE TITLE
deg to rad conversion

### ISSUE THREAD

**Issue by GilenTell** [ROS-Aceinna/ros_openimu#4]
Hi,
In openimu_driver.py is defined a conversion constant as:
`convert_rads = math.pi *2`
It is used to convert angular velocities like:
`imu_msg.angular_velocity.x = readback[4] / convert_rads`
I don't understand this conversion, because I supposed that the openIMU300ZI is sending this velocity in deg/s. So I expect that the conversion will be multiplying by:
`math.pi/180.0`
Is this a bug or the units of velocity are other?
Thank you,
Guillermo

**Comment by steveh-10** [comment]
thanks for spotting, the conversion should be from degrees to rads - update made

**Comment by GilenTell** [comment]
Thank you!
