### ISSUE TITLE
Publishing same data for magnetic field and angular rate

### ISSUE THREAD

**Issue by Krishnateja244** [ROS-Aceinna/ros_openimu#6]
Hello,
while working on my project I found out that angular rate and magnetic field values are publishing same values and found out that same bytes were given to angular rate and magnetic field.

![Screenshot from 2021-04-12 18-50-28](https://user-images.githubusercontent.com/33598476/114432407-f4526a00-9bc0-11eb-985d-dc641144c84a.png)

Regards,
Krishna.

**Comment by ROS-Aceinna** [comment]
thank you, update made

**Comment by Steveh-1000** [comment]
resolved - closed
