### ISSUE TITLE
Error when launching ROS node

### ISSUE THREAD

**Issue by Gaurav-Kapoor-07** [ROS-Aceinna/ros_openimu#7]
I am getting this error when I am launching the ROS node through `roslaunch ros_openimu openimu_driver.launch`.

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /
    openimu_driver (ros_openimu/openimu_driver.py)

auto-starting new master
process[master]: started with pid [14188]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 20e81e18-ca90-11eb-8a79-d5fbee0925d9
process[rosout-1]: started with pid [14198]
started core service [/rosout]
process[openimu_driver-2]: started with pid [14201]
start to find device
# Connected OpenIMU #
Device: OpenIMU300RI 5020-3309-01 1.1.3 SN:1903139141
Firmware: VG_AHRS_J1939 1.0.3
[INFO] [1623400595.631389]: OpenIMU driver initialized.
Traceback (most recent call last):
  File "/home/gaurav.kapoor/catkin_ws/src/ros_openimu/scripts/openimu_driver.py", line 57, in <module>
    readback = openimu_wrp.readimu()
  File "/home/gaurav.kapoor/catkin_ws/src/ros_openimu/scripts/openimu_driver.py", line 34, in readimu
    readback = self.openimudev.getdata('z1')
  File "/home/gaurav.kapoor/catkin_ws/src/ros_openimu/src/aceinna/tools/openimu.py", line 41, in getdata
    timeraw = (readback[0:4]) #time in ms
TypeError: 'NoneType' object is not subscriptable
[openimu_driver-2] process has died [pid 14201, exit code 1, cmd /home/gaurav.kapoor/catkin_ws/src/ros_openimu/scripts/openimu_driver.py __name:=openimu_driver __log:=/home/gaurav.kapoor/.ros/log/20e81e18-ca90-11eb-8a79-d5fbee0925d9/openimu_driver-2.log].
log file: /home/gaurav.kapoor/.ros/log/20e81e18-ca90-11eb-8a79-d5fbee0925d9/openimu_driver-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Is there something I need to install on my PC or send through the serial bus to activate the IMU? I have installed OpenIMU through pip and I am using ROS Noetic with Ubuntu 20.04. I am using the IMU through Serial to USB interface. My IMU model is OpenIMU300RI.

**Comment by steveh-10** [comment]
Hi, Is the OpenIMU300RI configured to send the z1 packet, also a non-zero packet rate? By default the RS232 connection packet rate is set to quiet. You can change this and save permanently in Aceinna navigation studio: https://developers.aceinna.com/

**Comment by tiesus** [comment]
I'am getting the same error, when I'm launching the driver. Imu is configured correctly to send z1 package. I checked that the packages are send with the tools from here https://developers.aceinna.com/. I can view the data stream there without any errors.
