### ISSUE TITLE
Ros Melodic Support

### ISSUE THREAD

**Issue by David9696** [ROS-Aceinna/ros_openimu#8]
Hi,

Is it possible to make this package compatible with ros Melodic? We have a robot which is using ros melodic. We would like to try openimu300zi with this robot. Hope you could help.

Thanks.

David

**Comment by nuagetec** [comment]
Hi,

I have the same request ...
I can't get this package to work with ROS Melodic. 
Melodic use python 2.7 I think is the issue.

Thanks,

Kévin

**Comment by ROS-Aceinna** [comment]
The driver was intended to work with Noetic and python 3.x.
